"""Create User Group Message tables

Revision ID: abbd7a993a30
Revises: 
Create Date: 2025-10-09 12:59:26.896362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abbd7a993a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('group_to_user',
    sa.Column('group_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'MEMBER_READ_ONLY', name='grouprole'), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['groups.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_uuid', 'user_uuid')
    )
    op.create_table('messages',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sending_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender_uuid', sa.UUID(), nullable=True),
    sa.Column('group_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_uuid'], ['groups.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('message_resource',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=256), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['message_uuid'], ['messages.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_resource')
    op.drop_table('messages')
    op.drop_table('group_to_user')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
